version: "3.8"

services:
  myapp:
    image: myapp:1.0.0  # Rule #9: Pin image version
    container_name: secure_myapp
    user: "1000:1000"   # Rule #2: Run as non-root user
    read_only: true     # Rule #8: Read-only root filesystem
    tmpfs:              # Rule #8: Temporary write access
      - /tmp
    deploy:
      resources:        # Rule #7: Limit resources
        limits:
          cpus: "0.5"
          memory: "512M"
    security_opt:       # Rule #4: Prevent privilege escalation
      - no-new-privileges:true
    cap_drop:           # Rule #3: Drop all Linux capabilities
      - ALL
    cap_add:            # Only add what is needed
      - CHOWN
    volumes:
      - ./config:/app/config:ro  # Rule #8: Mount as read-only
    networks:
      - isolated_network
    logging:            # Rule #10: Logging config (if using driver)
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  isolated_network:
    driver: bridge
